export default {
	build: {
		html: 'build',
		scripts: 'build/assets/js/',
		styles: 'build/assets/css/',
		images: 'build/assets/images/',
		fonts: 'build/assets/fonts/',
		sprites: 'build/assets/images/sprites/',
		svg: 'build/assets/svg/',
		json: 'build/assets/json/',
		videos: 'build/assets/video/',
	},
	src: {
		templates: './src/',
		njk: 'src/pages/**/*.njk',
		scripts: 'src/assets/js/index.js',
		styles: 'src/assets/styles/styles.scss',
		images: 'src/assets/images/**/*.*',
		rasterImages: 'src/assets/images/**/*.{jpg,png}',
		imagesInline: 'src/assets/images/inline/',
		fonts: 'src/assets/fonts/**/*.*',
		sprites: 'src/assets/images/sprites/*.png',
		svg: 'src/assets/svg/**/*.svg',
		json: 'data/**/*.json',
		videos: 'src/assets/video/**/*.*',
	},
	watch: {
		njk: ['src/**/*.njk', 'global-data.json'],
		scripts: 'src/**/*.js',
		styles: 'src/**/*.scss',
		images: 'src/assets/images/**/*.*',
		fonts: 'src/assets/fonts/**/*.*',
		sprites: 'src/assets/images/sprites/*.png',
		svg: 'src/assets/svg/**/*.svg',
		json: 'data/**/*.json',
	},
	clean: 'build/',
};
